import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ReCaptchaProvider from "@/components/app/ReCaptchaProvider";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

// tailwindcss classes:
// font-normal = inter regular
// font-medium = inter medium
// font-bold = inter bold

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <ReCaptchaProvider>{children}</ReCaptchaProvider>
      </body>
    </html>
  );
}
